### ISSUE TITLE
Vertaisarviointi 1

### ISSUE THREAD

**Issue by ellisrnm** [Doubleneck/RSA_IMPLEMENTAATIO#1]
Kloonattu: 18.8.22 klo 16.45

## Yleiset kommentit

Hyvää työtä!

Asennus- ja käyttöohjeet on kirjoitettu selkeästi ja niiden avulla oli helppo asentaa ja käynnistää ohjelma. Yleisesti ohjelman toiminta on selkeää ja toimivaa. Testasin ohjelmaa myös erilaisilla virheellisille syötteillä ja ohjelma toimi tarkoituksenmukaisesti myös silloin. Olet siis ottanut hyvin huomioon myös tällaiset tapaukset koodissa.

Myös koodi on helposti luettavaa. Pääsääntöisesti metodit on nimetty selkeästi ja niistä on helppo saada kiinni mitä koodi tekee.

## Mahdollisia kehityskohteita

- Metodin miller_rabin_check voisi selkeyttää. Metodin docstring on nyt “testaa onko annettu luku suurella todennäköisyydellä alkuluku” ja se palauttaa True jos näin on. Saman metodin sisällä määritelty yhden kierroksen funktio palauttaa kuitenkin arvon False, jos kyseessä on todennäköisesti alkuluku. Tämä ei ole välttämättä ole kaikki intuitiivisin valinta. 

- Ohjelmakoodista voisi poistaa toisteisuutta. Esimerkiksi nyt luokan RsaService metodit create_p ja create_q ovat isolta osalta samaa. Jos ohjelman logiikkaan haluttaisiin näiden funktioiden osalta muutoksia, tulee muutos tehdä kahteen paikkaan ja siinä tapahtuu helposti virheitä. Yhteiset osat näistä metodeista voisi yhdistää. Näin ei tarvitsisi myöskään testata molempia samanlaisilla testeillä erikseen.

- Tiedosto .pylintrc ei sisällä tällä hetkellä minkäänlaisia sääntöjä eli pylintin ajaminen ei taida tällä hetkellä tyylitarkistaa yhtään mitään? Kannattaa ottaa käyttöön vaikka suositeltu oletuskonfiguraatio tarkistettaville säännöille niin löydät koodista vielä pientä korjailtavaa.

- Ohjelma voisi olla vielä mukavampi käyttää, jos avaimen voisi tallentaa vaikkapa tiedostoon sen sijaan että käyttäjä kopioi ja liittää avaimia. Tämä toki ei ohjelman kannalta ole välttämätöntä.

**Comment by Doubleneck** [comment]
Kiitos kommenteista, kaikki ovat hyviä parannuksia, ruuvaan kuntoon , kun ehdin takas koneen ääreen.

Tuo, että avaimia ja viestejä ei talleteta tiedostoiksi johtuu siitä, että näin se on havainnollisempi esitellä demotilaisuudessa.

Kyllä toi lintteri aika paljon avusti ilman custom konfiguraatiota, se taitaa käyttää jotain omaa defaultia jos muuta ei ole annettu. Kokeilen silti jollain toisella konfiguraatiolla miten muuttuu.

Kiitokset!
