### ISSUE TITLE
Vertaisarvio

### ISSUE THREAD

**Issue by pontushed** [Doubleneck/RSA_IMPLEMENTAATIO#3]
Moi!

Hienoa työtä. Asennus oli helppoa. Salaus ja purkaminen toimi hyvin. Dokumentaatio on hyvällä mallilla ja testikattavuus on lähes täydellinen.

Koodi on mielestäni hyvin jaoteltu omiin kansioihin ja luokkiin, joten se on helppolukuista ja selkeää.
Jos haluat vielä viilata koodia, niin tyyppivinkit voisi lisätä funktioihin ja laajentaa docstringejä argumenttien ja palautusarvojen kera.

Yksi parannusehdotus minulla olisi käyttöliittymään:  jos käyttäjä on sitä tyyppiä, joka ei jaksa lukea käyttöohjetta kovin pitkälle, niin käyttöliittymä voisi ohjeistaa eri vaiheissa että "Tässä julkinen ja yksityinen avain, kopioi ne talteen" ja niin edelleen.

**Comment by Doubleneck** [comment]
Kiitos arviosta, hyviä pointteja, argumenttien ja parametrien lisääminen docstringeihin olikin tarkoitus vielä tehdä. 

Jatkokehitysideana oli mulla graafinen käyttöliittymä, en ehkä tässä välissä enää ruuvaa tuota tekstiliittymää, mutta hyvä vinkki sinänsä, en tullut edes ajatelleeksi että ui:ssa voiskin olla enemmän ohjeistusta tän tyyppisessä 👍
